export const routerPaths = {
  signIn: { url: '/signin' },
  signUp: { url: '/signup' },
  dasboard: { url: '/dashboard' },
  jobs: { url: '/jobs' },
  jobsId: { url: '/jobs/:id' },
  jobsEdit: { url: '/jobs/:id/edit' },
  jobsAdd: { url: '/jobs/add' },
  candidates: { url: '/candidates' },
  candidatesId: { url: '/candidates/:id' },
  candidatesEdit: { url: '/candidates/:id/edit' },
  candidatesAdd: { url: '/candidates/add' },
  profile: { url: '/profile' },
  blacklist: { url: '/blacklist' },
};
